# These are supported funding model platforms

github: [tortuvshin]
patreon: turtuvshin
open_collective: intelligo
ko_fi: turtuvshin
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
custom: # Replace with a single custom sponsorship URL
